services:
  db.zenon.frauds:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db_events
    ports:
      - "3306:3306"
    volumes:
      - mysql.db.events:/var/lib/mysql
volumes:
  mysql.db.events:

